on:
  pull_request:
    branches:
      - main
  push:

jobs:
  executa_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Action Checkout
        uses: actions/checkout@v2

      - name: Instala o Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Instala o Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.create false --local
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Instala as Dependências
        run: poetry install

      - name: Executa o Black
        run: poetry run black app --check
